// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EngSFTTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void engSFT() {
    // Test name: EngSFT
    // Step # | name | target | value
    // 1 | open | /src/View/Veiculos.php | 
    // -------------------Abertura, inspeção dos locais----------------
    driver.Navigate().GoToUrl("http://localhost/src/View/Veiculos.php");
    // 2 | setWindowSize | 1074x941 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1074, 941);
    // 3 | assertText | css=h1 | Veiculos
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Veiculos"));
    // 4 | assertElementPresent | css=button:nth-child(7) | 
    var elements = driver.FindElements(By.CssSelector("button:nth-child(7)"));
    Assert.True(elements.Count > 0);
    // 5 | assertElementPresent | css=button:nth-child(8) | 
    var elements = driver.FindElements(By.CssSelector("button:nth-child(8)"));
    Assert.True(elements.Count > 0);
    // 6 | click | css=button:nth-child(7) | 
    driver.FindElement(By.CssSelector("button:nth-child(7)")).Click();
    // 7 | assertText | css=h1 | Cadastro de veiculo
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Cadastro de veiculo"));
    // 8 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:\n\nVoltar
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:\\\\n\\\\nVoltar"));
    // 9 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:\n\nVoltar
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:\\\\n\\\\nVoltar"));
    // 10 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:\n\nVoltar
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:\\\\n\\\\nVoltar"));
    // 11 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:\n\nVoltar
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:\\\\n\\\\nVoltar"));
    // 12 | assertEditable | name=cano | 
    {
      var element = driver.FindElement(By.Name("cano"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.True(isEditable);
    }
    // 13 | assertEditable | name=cplaca | 
    {
      var element = driver.FindElement(By.Name("cplaca"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.True(isEditable);
    }
    // 14 | assertEditable | name=cmodelo | 
    {
      var element = driver.FindElement(By.Name("cmodelo"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.True(isEditable);
    }
    // 15 | assertEditable | name=cmarca | 
    {
      var element = driver.FindElement(By.Name("cmarca"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.True(isEditable);
    }
    // 16 | assertElementPresent | css=input:nth-child(13) | 
    var elements = driver.FindElements(By.CssSelector("input:nth-child(13)"));
    Assert.True(elements.Count > 0);
    // 17 | assertElementPresent | css=input:nth-child(14) | 
    var elements = driver.FindElements(By.CssSelector("input:nth-child(14)"));
    Assert.True(elements.Count > 0);
    // 18 | assertElementPresent | css=button | 
    var elements = driver.FindElements(By.CssSelector("button"));
    Assert.True(elements.Count > 0);
    // 19 | click | name=cano | 
    // ---------------------Inserção De Valores Na Tabela Veiculo----------------
    driver.FindElement(By.Name("cano")).Click();
    // 20 | type | name=cano | 1999
    driver.FindElement(By.Name("cano")).SendKeys("1999");
    // 21 | type | name=cplaca | AVC6666
    driver.FindElement(By.Name("cplaca")).SendKeys("AVC6666");
    // 22 | sendKeys | name=cplaca | ${KEY_ENTER}
    driver.FindElement(By.Name("cplaca")).SendKeys(Keys.Enter);
    // 23 | type | name=cmodelo | x6
    driver.FindElement(By.Name("cmodelo")).SendKeys("x6");
    // 24 | type | name=cmarca | tiberius
    driver.FindElement(By.Name("cmarca")).SendKeys("tiberius");
    // 25 | sendKeys | name=cmarca | ${KEY_ENTER}
    driver.FindElement(By.Name("cmarca")).SendKeys(Keys.Enter);
    // 26 | assertText | css=h1 | Veiculos
    // -------------Aba Veiculos Inspeção----------
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Veiculos"));
    // 27 | assertText | css=th:nth-child(1) | Marca
    Assert.That(driver.FindElement(By.CssSelector("th:nth-child(1)")).Text, Is.EqualTo("Marca"));
    // 28 | assertText | css=th:nth-child(2) | Modelo
    Assert.That(driver.FindElement(By.CssSelector("th:nth-child(2)")).Text, Is.EqualTo("Modelo"));
    // 29 | assertText | css=th:nth-child(3) | Ano
    Assert.That(driver.FindElement(By.CssSelector("th:nth-child(3)")).Text, Is.EqualTo("Ano"));
    // 30 | assertText | css=th:nth-child(4) | Placa
    Assert.That(driver.FindElement(By.CssSelector("th:nth-child(4)")).Text, Is.EqualTo("Placa"));
    // 31 | assertText | css=th:nth-child(5) | Opcoes
    Assert.That(driver.FindElement(By.CssSelector("th:nth-child(5)")).Text, Is.EqualTo("Opcoes"));
    // 32 | assertElementPresent | css=button:nth-child(8) | 
    var elements = driver.FindElements(By.CssSelector("button:nth-child(8)"));
    Assert.True(elements.Count > 0);
    // 33 | assertElementPresent | css=button:nth-child(9) | 
    var elements = driver.FindElements(By.CssSelector("button:nth-child(9)"));
    Assert.True(elements.Count > 0);
    // 34 | click | css=form:nth-child(1) img | 
    // -------EDITAR VEICULO---------
    driver.FindElement(By.CssSelector("form:nth-child(1) img")).Click();
    // 35 | assertText | css=h1 | Edicao de veiculo
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Edicao de veiculo"));
    // 36 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:"));
    // 37 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:"));
    // 38 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:"));
    // 39 | assertText | css=form | Ano:\n\nPlaca:\n\nModelo:\n\nMarca:
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Ano:\\\\n\\\\nPlaca:\\\\n\\\\nModelo:\\\\n\\\\nMarca:"));
    // 40 | assertElementPresent | css=input:nth-child(13) | 
    var elements = driver.FindElements(By.CssSelector("input:nth-child(13)"));
    Assert.True(elements.Count > 0);
    // 41 | click | css=html | 
    driver.FindElement(By.CssSelector("html")).Click();
    // 42 | type | name=cmodelo | X7
    driver.FindElement(By.Name("cmodelo")).SendKeys("X7");
    // 43 | click | name=cmarca | 
    driver.FindElement(By.Name("cmarca")).Click();
    // 44 | type | name=cmarca | TesteEdicao
    driver.FindElement(By.Name("cmarca")).SendKeys("TesteEdicao");
    // 45 | click | css=form | 
    driver.FindElement(By.CssSelector("form")).Click();
    // 46 | click | css=input:nth-child(13) | 
    driver.FindElement(By.CssSelector("input:nth-child(13)")).Click();
    // 47 | click | css=form:nth-child(2) > button | 
    // ---------------Exclusao-----------------
    driver.FindElement(By.CssSelector("form:nth-child(2) > button")).Click();
    // 48 | click | css=button:nth-child(7) | 
    // ---------Cadastra novo veiculo----------
    driver.FindElement(By.CssSelector("button:nth-child(7)")).Click();
    // 49 | click | name=cano | 
    driver.FindElement(By.Name("cano")).Click();
    // 50 | type | name=cano | 1999
    driver.FindElement(By.Name("cano")).SendKeys("1999");
    // 51 | type | name=cplaca | ABC1234
    driver.FindElement(By.Name("cplaca")).SendKeys("ABC1234");
    // 52 | type | name=cmodelo | teste1
    driver.FindElement(By.Name("cmodelo")).SendKeys("teste1");
    // 53 | type | name=cmarca | teste1
    driver.FindElement(By.Name("cmarca")).SendKeys("teste1");
    // 54 | click | css=html | 
    driver.FindElement(By.CssSelector("html")).Click();
    // 55 | click | css=input:nth-child(13) | 
    driver.FindElement(By.CssSelector("input:nth-child(13)")).Click();
    // 56 | click | css=button:nth-child(9) | 
    driver.FindElement(By.CssSelector("button:nth-child(9)")).Click();
    // 57 | assertElementPresent | css=button:nth-child(9) | 
    // -----------ABA SERVIÇO--------------
    var elements = driver.FindElements(By.CssSelector("button:nth-child(9)"));
    Assert.True(elements.Count > 0);
    // 58 | assertText | css=h1 | Servicos
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Servicos"));
    // 59 | assertText | css=h2 | Orcamentos
    Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("Orcamentos"));
    // 60 | assertElementPresent | css=button:nth-child(9) | 
    var elements = driver.FindElements(By.CssSelector("button:nth-child(9)"));
    Assert.True(elements.Count > 0);
    // 61 | assertElementPresent | css=button:nth-child(10) | 
    var elements = driver.FindElements(By.CssSelector("button:nth-child(10)"));
    Assert.True(elements.Count > 0);
    // 62 | click | css=button:nth-child(9) | 
    // ------------------Cadastrar Orçamento--------------
    driver.FindElement(By.CssSelector("button:nth-child(9)")).Click();
    // 63 | assertText | css=h1 | Cadastro de novo orcamento
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Cadastro de novo orcamento"));
    // 64 | assertText | css=form | Veiculo:\nteste1 teste1\n\n\nDescricao:\n\n\n\n\nVoltar
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Veiculo:\\\\nteste1 teste1\\\\n\\\\n\\\\nDescricao:\\\\n\\\\n\\\\n\\\\n\\\\nVoltar"));
    // 65 | assertText | css=form | Veiculo:\nteste1 teste1\n\n\nDescricao:\n\n\n\n\nVoltar
    Assert.That(driver.FindElement(By.CssSelector("form")).Text, Is.EqualTo("Veiculo:\\\\nteste1 teste1\\\\n\\\\n\\\\nDescricao:\\\\n\\\\n\\\\n\\\\n\\\\nVoltar"));
    // 66 | assertEditable | name=cplaca | 
    {
      var element = driver.FindElement(By.Name("cplaca"));
      Boolean isEditable = element.Enabled && element.GetAttribute("readonly") == null;
      Assert.True(isEditable);
    }
    // 67 | assertElementPresent | css=input:nth-child(10) | 
    var elements = driver.FindElements(By.CssSelector("input:nth-child(10)"));
    Assert.True(elements.Count > 0);
    // 68 | assertElementPresent | css=input:nth-child(11) | 
    var elements = driver.FindElements(By.CssSelector("input:nth-child(11)"));
    Assert.True(elements.Count > 0);
    // 69 | assertElementPresent | css=button | 
    var elements = driver.FindElements(By.CssSelector("button"));
    Assert.True(elements.Count > 0);
    // 70 | click | name=cdescricao | 
    driver.FindElement(By.Name("cdescricao")).Click();
    // 71 | click | css=form | 
    driver.FindElement(By.CssSelector("form")).Click();
    // 72 | type | name=cdescricao | Trocar Cambio do Fiat Palio 2010, 1.0, flex
    // --------------Editar Descricao------------------
    driver.FindElement(By.Name("cdescricao")).SendKeys("Trocar Cambio do Fiat Palio 2010, 1.0, flex");
    // 73 | click | css=form | 
    driver.FindElement(By.CssSelector("form")).Click();
    // 74 | click | name=cdescricao | 
    driver.FindElement(By.Name("cdescricao")).Click();
    // 75 | click | name=cdescricao | 
    driver.FindElement(By.Name("cdescricao")).Click();
    // 76 | click | css=input:nth-child(11) | 
    // ----Limpa Descrição --- 
    driver.FindElement(By.CssSelector("input:nth-child(11)")).Click();
    // 77 | type | name=cdescricao | Trocar Cambio do Fiat Palio 2010, 1.0, flex
    driver.FindElement(By.Name("cdescricao")).SendKeys("Trocar Cambio do Fiat Palio 2010, 1.0, flex");
    // 78 | click | css=form | 
    driver.FindElement(By.CssSelector("form")).Click();
    // 79 | click | css=input:nth-child(10) | 
    // ------Registrar-----
    driver.FindElement(By.CssSelector("input:nth-child(10)")).Click();
    // 80 | click | css=form:nth-child(1) img | 
    // -----------EDITAR ORCAMEMTO-----------
    driver.FindElement(By.CssSelector("form:nth-child(1) img")).Click();
    // 81 | mouseDownAt | name=cdescricao | 330.00471687316895,20.339614868164062
    {
      var element = driver.FindElement(By.Name("cdescricao"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    // 82 | mouseMoveAt | name=cdescricao | 330.00471687316895,20.339614868164062
    {
      var element = driver.FindElement(By.Name("cdescricao"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 83 | mouseUpAt | name=cdescricao | 330.00471687316895,20.339614868164062
    {
      var element = driver.FindElement(By.Name("cdescricao"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    // 84 | click | name=cdescricao | 
    driver.FindElement(By.Name("cdescricao")).Click();
    // 85 | type | name=cdescricao | Trocar Cambio do Fiat Palio 2010, 1.0, flex\nEditar1.0
    driver.FindElement(By.Name("cdescricao")).SendKeys("Trocar Cambio do Fiat Palio 2010, 1.0, flex\\nEditar1.0");
    // 86 | click | css=input:nth-child(10) | 
    driver.FindElement(By.CssSelector("input:nth-child(10)")).Click();
    // 87 | click | css=form:nth-child(2) img | 
    // -------------EXCLUIR ORÇAMENTO------------
    driver.FindElement(By.CssSelector("form:nth-child(2) img")).Click();
    // 88 | click | css=button:nth-child(10) | 
    // -----------VOLTAR ABA VEICULO------------------------
    driver.FindElement(By.CssSelector("button:nth-child(10)")).Click();
    // 89 | click | css=form:nth-child(2) img | 
    // ------EXCLUIR VEICULO ------
    driver.FindElement(By.CssSelector("form:nth-child(2) img")).Click();
    // 90 | click | css=html | 
    // -------FIM DO TESTE----------------
    driver.FindElement(By.CssSelector("html")).Click();
  }
}
